name: "Deploy Portfolio"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy Portfolio Website"
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create terraform.tfvars
        working-directory: environments/dev
        run: |
          echo "bucket_name = \"${{ secrets.BUCKET_NAME }}\"" >> terraform.tfvars
          echo "domain_name = \"${{ secrets.DOMAIN_NAME }}\"" >> terraform.tfvars

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -no-color -input=false -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -auto-approve tfplan
